[phases.build]
cmds = [
  "npm install",
  "npx update-browserslist-db@latest",
  "npx vite build",
  "npx esbuild server/index.ts --platform=node --packages=external --bundle --format=esm --outdir=dist"
]

[phases.start]
cmd = "node server.js"

[variables]
NODE_ENV = "production"