[phases.build]
cmds = [
  "npm ci",
  "node comprehensive-supabase-migration.js"
]

[phases.start]
cmd = "cd dist && npm start"

[variables]
NODE_ENV = "production"
SUPABASE_URL = "https://kwdzbssuovwemthmiuht.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt3ZHpic3N1b3Z3ZW10aG1pdWh0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1NDEyMDYsImV4cCI6MjA2NzExNzIwNn0.7AGomhrpXHBnSgJ15DxFMi80E479S9w9mIeqMnsvNrA"