services:
  - type: web
    name: dukafiti
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: node server.js
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production